config/routes.rb
ReadyInvoice::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  resources :invoices
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action :set_pg_constants, only: [:show, :index]
  before_action :find_pg_invoice, only: [:show]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = PG::Invoice__c.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  def show
    @line_items = PG::Line_Item__c.where("Invoice__c" => @invoice.Id )
    merchandise_ids = @line_items.map(&:Merchandise__c)
    @merchandise = PG::Merchandise__c.where("Id" => merchandise_ids)

    respond_to do |format|
      format.html do
        render :template => 'invoices/pdf.html.erb',
               :layout => 'pdf_layout'
      end

      format.pdf do
        @example_text = "some text"
        render :pdf => "file_name",
               :template => 'invoices/pdf.html.erb',
               :layout => 'pdf_layout',
               :footer => {
                  :center => "Center",
                  :left => "Left",
                  :right => "Right"
                           }
      end
    end
  end


  private

  def set_pg_constants
    current_user.salesforce.sf_models.each { |m| m.reload }
  end

  def find_pg_invoice
    @invoice = PG::Invoice__c.find(params[:id])
  end
end

app/views/invoices/index.html.erb
<div class="row collapse">
  <h1>Listing Invoices</h1>

  <table class="table" class="responsive">
    <tr>
      <th>Invoice Name</th>
      <th>Total</th>
      <th>Status</th>
      <th></th>
      <th></th>
    </tr>

  <% @invoices.each do |invoice| %>
    <tr class="<%= (invoice.Name == 'Closed Won') ? "success" : "warning"%> ">
      <td><%= invoice.Name %></td>
      <td><%= invoice.Invoice_Total__c %></td>
      <td><%= invoice.Status__c %></td>
      <td><%= link_to 'Create PDF document', invoice_path(invoice, format: :pdf) %></td>
      <td><%= link_to 'Edit PDF document', invoice_path(invoice) %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/invoices/pdf.html.erb
<header>
  <h1>Invoice</h1>
  <address contenteditable="">
    <p>Jonathan Neal</p>
    <p>101 E. Chapman Ave<br>Orange, CA 92866</p>
    <p>(800) 555-1234</p>
  </address>
  <span><img alt="" src="logo.png" class=""><input type="file" accept="image/*"></span>
</header>
<article>
  <h1>Recipient</h1>
  <address contenteditable="">
    <p>Some Company<br>c/o Some Guy</p>
  </address>
  <table class="meta">
    <tbody><tr>
      <th><span contenteditable="">Invoice #</span></th>
      <td><span contenteditable=""><%= @invoice.Name %></span></td>
    </tr>
    <tr>
      <th><span contenteditable="">Date</span></th>
      <td><span contenteditable=""><%= Date.today.strftime('%B %e, %Y') %></span></td>
    </tr>
    <tr>
      <th><span contenteditable="">Amount Due</span></th>
      <td><span id="prefix" contenteditable="">$</span><span>600.00</span></td>
    </tr>
  </tbody></table>
  <table class="inventory">
    <thead>
      <tr>
        <th><span contenteditable="">Name</span></th>
        <th><span contenteditable="">Description</span></th>
        <th><span contenteditable="">Rate</span></th>
        <th><span contenteditable="">Quantity</span></th>
        <th><span contenteditable="">Price</span></th>
      </tr>
    </thead>
    <tbody>

      <% @line_items.each do |li| %>
        <tr>
          <td><a class="cut">-</a><span contenteditable=""><%= li.Name %></span></td>
          <td><span contenteditable=""></span></td>
          <td><span data-prefix="">$</span><span contenteditable=""><%= li.Unit_Price__c %></span></td>
          <td><span contenteditable=""><%= li.Quantity__c %></span></td>
          <td><span data-prefix="">$</span><span>600.00</span></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <a class="add">+</a>
  <table class="balance">
    <tbody><tr>
      <th><span contenteditable="">Total</span></th>
      <td><span data-prefix="">$</span><span>600.00</span></td>
    </tr>
    <tr>
      <th><span contenteditable="">Amount Paid</span></th>
      <td><span data-prefix="">$</span><span contenteditable="">0.00</span></td>
    </tr>
    <tr>
      <th><span contenteditable="">Balance Due</span></th>
      <td><span data-prefix="">$</span><span>600.00</span></td>
    </tr>
  </tbody></table>
</article>
<aside>
  <h1><span contenteditable="">Additional Notes</span></h1>
  <div contenteditable="">
    <p>A finance charge of 1.5% will be made on unpaid balances after 30 days.</p>
  </div>
</aside>