config/routes.rb
ReadyInvoice::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  resources :invoices
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar="">
  <ul class="title-area">
     <li class="name">
       <h1><%= link_to "Databasedotcom", root_path, :class => 'brand' %></a></h1>
     </li>
     <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <% if user_signed_in? %>
        <li>
        <%= link_to 'Logout', signout_path %>
        </li>
      <% else %>
        <li>
        <%= link_to 'Login', signin_path %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <% if current_user.has_role? :admin %>
          <li>
          <%= link_to 'Admin', users_path %>
          </li>
        <% end %>
        <li>
         <%= link_to 'Invoices', invoices_path %>
        </li>
        <li>
          <%= link_to "Signed in as: #{current_user.name}", "#" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ready Invoice" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ready Invoice" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="row">
      <div class="large-8 columns">
        <%= yield %>
      </div>

      <div class="large-4 columns">
        <h2>About Us</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/pdf_layout.html.erb
<!DOCTYPE html>
<html><head><style>article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio[controls],canvas,video{display:inline-block}[hidden],audio{display:none}mark{background:#FF0;color:#000}</style>
    <meta charset="utf-8">
    <title>Invoice</title>
    <link rel="stylesheet" href="style.css">
    <link rel="license" href="http://www.opensource.org/licenses/mit-license/">
    <script src="script.js"></script>
    <%= wicked_pdf_stylesheet_link_tag "documents" %>
    <%#= wicked_pdf_image_tag %>
    <%= wicked_pdf_javascript_include_tag "invoice" %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf_layout.pdf.erb
<!DOCTYPE html>
<html><head><style>article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio[controls],canvas,video{display:inline-block}[hidden],audio{display:none}mark{background:#FF0;color:#000}</style>
    <meta charset="utf-8">
    <title>Invoice</title>
    <link rel="stylesheet" href="style.css">
    <link rel="license" href="http://www.opensource.org/licenses/mit-license/">
    <script src="script.js"></script>
    <%= wicked_pdf_stylesheet_link_tag %>
    <%#= wicked_pdf_image_tag %>
    <%= wicked_pdf_javascript_include_tag %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
  </body>
</html>